Solution to 0532 - K-diff Pairs in an Array #263
vJechsmayr/PythonAlgorithms pull request #272
Opened 2020-10-04 19:36 UTC by anuranjanpandey

**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [ ] I have read the CONTRIBUTING document.
* [ ] My code is written in **Python3** and is ending with _.py_
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] I have checked that my submission does pass the test on LeetCode.com 
* [ ] Does your filename follow the naming Conventions?
* [ ] Have you linked your PR to an Issue?

**Closing issues**

Put `closes #263 ` in your comment to auto-close the issue that your PR fixes (if such).

2020-10-04 19:59 UTC, vJechsmayr commented on LeetCode/0523_K_diff_Pairs_in_an_Array.py
> +    def findPairs(self, nums: List[int], k: int) -> int:
Make sure you fit the naming of the code from the issue.

2020-10-04 19:59 UTC, vJechsmayr requested changes
Please check your Algorithm once more - there is an problem with an Test case on LeetCode:

![image](https://user-images.githubusercontent.com/6342890/95025811-d691ce80-068c-11eb-9603-f96f56be8168.png)

[https://leetcode.com/problems/continuous-subarray-sum/submissions/](https://leetcode.com/problems/continuous-subarray-sum/submissions/)

2020-10-04 20:48 UTC, Vulwsztyn commented on LeetCode/0523_K_diff_Pairs_in_an_Array.py
> +        return ans
no endline at the end of file

2020-10-05 03:23 UTC, anuranjanpandey commented
> Please check your Algorithm once more - there is an problem with an Test case on LeetCode:
> 
> ![image](https://user-images.githubusercontent.com/6342890/95025811-d691ce80-068c-11eb-9603-f96f56be8168.png)
> 
> https://leetcode.com/problems/continuous-subarray-sum/submissions/

![Screenshot (59)](https://user-images.githubusercontent.com/53137708/95037273-12a64d00-06e8-11eb-87d4-533efec31edf.png)

2020-10-05 09:39 UTC, vJechsmayr approved these changes
Thank you for contributing to my #hacktoberfest Repository!
Happy Hacktoberfest!

2020-10-05 09:39 UTC, merged