Add 1340. Jump Game V
vJechsmayr/PythonAlgorithms pull request #543
Opened 2020-10-10 01:26 UTC by livace

**IMPORTANT: Please do not create a Pull Request without an issue.**

### All Submissions:

* [x] I have read the CONTRIBUTING document.
* [x] My code is written in **Python3** and is ending with _.py_
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] I have checked that my submission does pass the test on LeetCode.com 
* [x] Does your filename follow the naming Conventions?
* [x] Have you linked your PR to an Issue?

**Closing issues**

closes #542

2020-10-10 13:48 UTC, vJechsmayr requested changes
Please check code again - Runtime Error

2020-10-10 13:48 UTC, vJechsmayr commented on LeetCode/1340_Jump_Game_V.py
> +            max_h = None
Code does not pass Test on LeetCode

![image](https://user-images.githubusercontent.com/6342890/95656648-0834ea80-0b10-11eb-8cd3-c5e6ce47b586.png)

2020-10-11 00:18 UTC, livace commented
Oh, my fault. Now everything should be fine

2020-10-28 07:40 UTC, vJechsmayr approved these changes
Thanks for contributing - Merged!

Runtime: 768 ms

Happy Hacktoberfest!

2020-10-28 07:40 UTC, merged